spring.application.name=SQSTest
aws.sqs.accessKeyId=accessKey
aws.sqs.secret.accessKeyId=secretAccessKey
aws.sqs.highPriorityQueueUrl=highPriorityQueue
aws.sqs.normalPriorityQueueUrl=normalPriorityQueue
